<?php

namespace frontend\controllers;

use frontend\resource\Comment;
use frontend\resource\Post;
use yii\db\ActiveRecord;
use yii\filters\auth\HttpBearerAuth;
use yii\web\ForbiddenHttpException;

class ActiveController extends \yii\rest\ActiveController
{
    public function behaviors(): array
    {
        $parentBehaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $parentBehaviors['authenticator']['only'] = ['create', 'update', 'delete'];
        $parentBehaviors['authenticator']['authMethods'] = [
            HttpBearerAuth::class
        ];

        return $parentBehaviors;
    }

    /**
     * @param string $action
     * @param ActiveRecord $model
     * @param array $params
     * @return void
     * @throws ForbiddenHttpException
     */
    public function checkAccess($action, $model = null, $params = []): void
    {
        // \Yii::$app->user current user
        if (in_array($action, ['update', 'delete']) && $model->created_by !== \Yii::$app->user->id) {
            throw new ForbiddenHttpException('you do not have permission to do this');
        }
    }
}